queues:
  - name: git-mirror
    bindings:
      - exchange: plus2.git
        kind: topic
        key: push.#

response_exchange:
  kind: topic
  name: plus2.messages
  key: campfire.General

env:
  mirrors: ~/mirrors
